# Workflow
name : First Workflow

on :
  push :
    workflow_dispatch :

jobs :

  Hello-Jobs :
    runs-on : ubuntu-latest
    steps:
      - name : Hello world
        run : echo "Hello World gitHub"
