# Workflow
name : First Workflow

on :
  push :
    workflow_dispatch :

jobs :

  Hello-Jobs :
    runs-on : ubuntu-latest
    steps:
      - name : Hello world
        run : echo "Hello World gitHub"

      - name : Multi-line bash
        run : |
          echo "I am "
          echo "a multi-line"
          echo "script"

  echo-goodbye :
    needs : Hello-Job
    runs-on : ubuntu-slim
    steps :
      -name : Say Goodbye
        run : echo "Goodbye"
